language: php

sudo: true

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

git:
  depth: 1

services:
  - redis-server
  - docker

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  - docker run -d --restart=always --name rabbitmq -p 4369:4369 -p 5673:5672 -p 15672:15672 -p 25672:25672 rabbitmq:management-alpine
  - docker run --rm -d -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=true --name mysql mysql/mysql-server:5.7
  - bash test/_ci/install_swoole.sh
  - phpenv config-rm xdebug.ini
  - phpenv config-add test/_ci/ci.ini
  - bash test/_ci/setup_dbs.sh

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer install --prefer-dist --optimize-autoloader
  - cp .env.example .env
  - bin/swoft app:init
  - bin/swoft start -d
  - sleep 10

script:
#  - ./vendor/bin/phpstan analyse app
  - ./vendor/bin/phpunit
