language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

git:
  depth: 1

services:
  - redis-server

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  - git checkout test
  - wget https://github.com/redis/hiredis/archive/v0.13.3.tar.gz -O hiredis.tar.gz && mkdir -p hiredis && tar -xf hiredis.tar.gz -C hiredis --strip-components=1 && cd hiredis && sudo make -j$(nproc) && sudo make install && sudo ldconfig && cd ..
  - printf "\n" | pecl install -f swoole
  - phpenv config-rm xdebug.ini
  - bash test/_ci/setup_dbs.sh

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer install --prefer-dist --optimize-autoloader
  - cp .env.example .env
  - bin/swoft app:init

script: composer test
